import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";
import Footer from "@/components/layout/footer";
import ConditionalTopBar from "@/components/layout/conditional-top-bar";
import { RouteLoadingOverlay } from "@/components/loading/route-loading";
import { ScrollToTop } from "@/components/layout/scroll-to-top";
import { AnalyticsTracker } from "@/components/analytics/analytics-tracker";
import { getSettings } from "@/services/server/settings-service";
import { stripHtml } from "@/lib/utils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const PLACEHOLDER_SETTINGS = {
  phoneNumber: "+90 (212) 555 00 00",
  address: "Örnek Mah. Örnek Sk. No:1, İstanbul",
  email: "info@example.com",
  instagramUrl: "#",
  linkedinUrl: "#",
} as const;

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let topBarProps = {
    address: PLACEHOLDER_SETTINGS.address,
    email: PLACEHOLDER_SETTINGS.email,
    instagramUrl: PLACEHOLDER_SETTINGS.instagramUrl,
    linkedinUrl: PLACEHOLDER_SETTINGS.linkedinUrl,
  };
  let footerSettings = {
    phoneNumber: PLACEHOLDER_SETTINGS.phoneNumber,
    email: PLACEHOLDER_SETTINGS.email,
    address: PLACEHOLDER_SETTINGS.address,
    instagramUrl: PLACEHOLDER_SETTINGS.instagramUrl,
    linkedinUrl: PLACEHOLDER_SETTINGS.linkedinUrl,
  };

  try {
    const page = await getSettings("", 0, 1, "id,asc");
    const s = page?.content?.[0];
    if (s) {
      topBarProps = {
        address: stripHtml(s.address ?? topBarProps.address),
        email: stripHtml(s.email ?? topBarProps.email),
        instagramUrl: s.instagramUrl ?? topBarProps.instagramUrl,
        linkedinUrl: s.linkedinUrl ?? topBarProps.linkedinUrl,
      };
      footerSettings = {
        phoneNumber: stripHtml(s.phoneNumber ?? footerSettings.phoneNumber),
        email: stripHtml(s.email ?? footerSettings.email),
        address: stripHtml(s.address ?? footerSettings.address),
        instagramUrl: s.instagramUrl ?? footerSettings.instagramUrl,
        linkedinUrl: s.linkedinUrl ?? footerSettings.linkedinUrl,
      };
    }
  } catch {
    // placeholder değerler kullanılır
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ScrollToTop />
        <AnalyticsTracker />
        <ConditionalTopBar {...topBarProps} />
        <Header />
        <RouteLoadingOverlay />
        {children}
        <Footer
          phoneNumber={footerSettings.phoneNumber}
          email={footerSettings.email}
          address={footerSettings.address}
          instagramUrl={footerSettings.instagramUrl}
          linkedinUrl={footerSettings.linkedinUrl}
        />
      </body>
    </html>
  );
}
